config/routes.rb
NegocioChimbarongo::Application.routes.draw do

  get "welcome/index"

  devise_for :usuarios
  
  devise_scope :usuario do
    authenticated :usuario do
      root 'welcome#index'

      get "sign_out", :to => "devise/sessions#destroy"
      resources :usuarios

      resources :pagos

      match 'pagos' => 'pagos#seleccionar', :via => :get, as: :seleccionar

      match 'pagos/cliente/:id' => 'pagos#pagos', :via => :get, as: :pagos_cliente

      match 'pagos/pagar/venta/:id' => 'pagos#pagar', :via => :get, as: :pagar_venta

      match 'pagos/abonar/venta' => 'pagos#abonar', :via => :get, as: :abonar_venta

      match 'pagos/abonar/venta' => 'pagos#agregar_abono', :via => :post, as: :agregar_abono

      resources :alerta

      resources :tipo_productos

      resources :articulos

      resources :productos

      match 'venta/articulos' => 'venta#articulos', :via => :get, as: :articulos_venta

      match 'venta/articulos' => 'venta#articulos_credito', :via => :get, as: :articulos_credito

      match 'venta/creditos' => 'venta#credito', :via => :get, as: :credito

      match 'venta/creditos' => 'venta#seleccionar_cliente', :via => :post, as: :seleccionar_cliente

      match 'venta/articulos' => 'venta#agregar_articulos', :via => :post, as: :agregar_articulos

      get 'venta/:id/articulos/' => 'venta#venta_lista', as: :venta_lista

      get 'venta/cancelar' => 'venta#cancelar_venta', as: :cancelar_venta

      resources :venta

      resources :clientes

    end

    unauthenticated do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/controllers/venta_controller.rb
class VentaController < ApplicationController
  layout "dashboard"
  before_action :set_ventum, only: [:show, :edit, :update, :destroy]

  # GET /venta
  # GET /venta.json
  def index
    @filterrific = initialize_filterrific(
      Ventum,
      params[:filterrific]
    ) or return
    
    @venta = Ventum.filterrific_find(@filterrific).paginate(:page => params[:page])
    

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /venta/1
  # GET /venta/1.json
  def show
    @articulos = Articulo.where(:ventum_id => params[:id])
  end

  # GET /venta/new
  def new
    @ventum = Ventum.create(:usuario_id => current_usuario.id, :total => 0, :fecha => Date.today )
    session[:ventum_id] = @ventum.id
  end

  def articulos
    @ventum = Ventum.find(session[:ventum_id].to_i)
    if @ventum.cliente_id == nil
      @ventum.pagado = true
      @ventum.save!
    end
    @articulos = Articulo.where(:ventum_id => session[:ventum_id])
  end

  def articulos_credito
    @ventum = Ventum.find(session[:ventum_id].to_i)
    if @ventum.cliente_id == nil
      @ventum.pagado = true
      @ventum.save!
    end
    @articulos = Articulo.where(:ventum_id => session[:ventum_id])
  end

  def credito
    @ventum = Ventum.find(session[:ventum_id].to_i)
    @clientes = Cliente.all
  end

  def seleccionar_cliente
    @ventum = Ventum.find(session[:ventum_id].to_i)
    @ventum.cliente_id = params[:cliente].to_i
    @ventum.save!
    flash[:notice] = "El cliente ha sido seleccionado"
    redirect_to action: "articulos_credito"
  end

  def agregar_articulos
    @ventum = Ventum.find(session[:ventum_id].to_i)
    producto = Producto.find_by(:codigo => params[:codigo])
    if producto == nil
      flash[:notice] = "El producto no se encuentra disponible"
      redirect_to action: "articulos" 
      
    else
      articulo_existente = Articulo.find_by(:ventum_id => @ventum.id, :producto_id => producto.id)

      if articulo_existente != nil
        articulo_existente.cantidad = articulo_existente.cantidad + params[:cantidad].to_i
        @ventum.total += producto.valor * params[:cantidad].to_i
        @ventum.save!
        articulo_existente.save!
        flash[:notice] = "El producto se ha modificado correctamente"
        redirect_to action: "articulos"
      elsif producto
        articulo = Articulo.create(:ventum_id => session[:ventum_id], :producto_id => producto.id, :cantidad => params[:cantidad], :total => params[:cantidad].to_i * producto.valor) 
        @ventum.total += producto.valor * params[:cantidad].to_i
        @ventum.save!
        flash[:notice] = "El producto se ha agregado correctamente"
        redirect_to action: "articulos"
      else
        flash[:notice] = "El producto no se encuentra disponible"
        redirect_to action: "articulos"
      end
    end
  end

  def venta_lista
    @ventum = Ventum.find(session[:ventum_id].to_i)
    @articulos = Articulo.where(:ventum_id => session[:ventum_id])

    aux = true
    @articulos.each do |a|
      aux = false
    end

    if !aux
      @ventum.terminada = true
      @articulos.each do |a|
        producto = Producto.find(a.producto_id)
        producto.stock -= a.cantidad
        producto.save!
      end
      @ventum.save!
    end
    flash[:notice] = 'La venta ha sido guardada con exito'
    redirect_to @ventum 
  end

  def cancelar_venta
    @ventum = Ventum.find(session[:ventum_id].to_i)
    @articulos = Articulo.where(:ventum_id => @ventum.id)

    @ventum.destroy
    flash[:notice] = "No se ha guardado la venta"
    redirect_to :venta
  end

  # GET /venta/1/edit
  def edit
  end

  # POST /venta
  # POST /venta.json
  def create
    @ventum = Ventum.new(ventum_params)

    respond_to do |format|
      if @ventum.save
        @carrito.each  do |c|
          @articulo = Articulo.create({:venta_id => @ventum.id, :producto_id => c.producto.id, :cantidad => c.cantidad})
        end
        format.html { redirect_to @ventum, notice: 'La venta ha sido guardada con exito' }
        format.json { render action: 'show', status: :created, location: @ventum }
      else
        format.html { render action: 'new' }
        format.json { render json: @ventum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /venta/1
  # PATCH/PUT /venta/1.json
  def update
    respond_to do |format|
      if @ventum.update(ventum_params)
        format.html { redirect_to @ventum, notice: 'La venta ha sido actualizada con exito' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ventum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /venta/1
  # DELETE /venta/1.json
  def destroy
    @ventum.destroy
    respond_to do |format|
      format.html { redirect_to venta_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ventum
      @ventum = Ventum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ventum_params
      params.require(:ventum).permit(:usuario_id, :total)
    end

end

app/helpers/venta_helper.rb
module VentaHelper
end

app/views/venta/articulos.html.erb
<div class="page-header position-relative">
    <h1>
        Carrito de Compras
        <small>
            <i class="fa fa-angle-double-right"></i>
            Lista de Artículos
        </small>
    </h1>
</div><!--/.page-header-->

<% if current_usuario.tipo_usuario != 0 %>
<div class="row-fluid">
  <div class="span12">
    <!--PAGE CONTENT BEGINS-->
    <div class="row-fluid">
      <h3 class="header smaller lighter green">Agregar Artículos</h3>
    </div>

    <%= form_tag :action => "agregar_articulos", :html => {:role => "form", :class => "form-inline"} do %>
      
      <div class="input-prepend">
        <span class="add-on">
          <i class="fa fa-barcode"></i>
        </span>
        <%= text_field_tag :codigo, nil, :autofocus => true, :autocomplete => "off", :placeholder => "Código de barra" %>
      </div>

      <div class="input-prepend">
        <span class="add-on">
          <i class="fa fa-cube"></i>
        </span>
        <%= text_field_tag :cantidad, "1", :autocomplete => "off", :placeholder => "Cantidad de productos" %>
      </div>

      <%= submit_tag "Agregar", :class => "btn btn-sm btn-success" %>
    <% end %>
  
    <div class="row-fluid">
      <h3 class="header smaller lighter green">Lista de Artículos</h3>
    </div>

    <% if @articulos == nil %>
      <p>No existen productos ingresados al carrito</p>

    <% else %>
      <div class="row-fluid">
        <div class="span12">
          <table id="sample-table-1" class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Subtotal</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @articulos.each do |articulo| %>
                <tr>
                  <td><%= Producto.find(articulo.producto_id).nombre %></td>
                  <td><%= articulo.cantidad %></td>
                  <td><%= Producto.find(articulo.producto_id).valor * articulo.cantidad %></td>
                  <td>
                    <%= link_to articulo, method: :delete, data: { confirm: '¿Estás seguro que deseas eliminar el articulo?'}, :class => "btn btn-mini btn-danger", :rel => "tooltip", :title => "Eliminar artículo" do%>
                      <i class="fa fa-trash bigger-120"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>  
            </tbody>
          </table>
        </div>
      </div>
      <div class="hr hr8 hr-double hr-dotted"></div>

      <div class="row-fluid">
        <div class="span5 pull-right">
          <h4 class="pull-right">
            Total Venta :
            <span class="red"> $<%= @ventum.total %></span>
          </h4>
        </div>
        <div class="span7 pull-left"> Información extra </div>
      </div>
    <% end %>
  </div>
</div>
<div class = "form-inline">
  <%= link_to venta_lista_path(@ventum), data: { confirm: '¿La venta está lista?' }, :class => "btn btn-primary" do %>
    <i class="fa fa-check"></i>
    Listo
  <% end %>

  <%= link_to cancelar_venta_path, data: {confirm: '¿Esta seguro que quiere cancelar la venta?'}, :class => "btn btn-warning" do %>
    <i class="fa fa-times"></i>
    Cancelar
  <% end %>
</div>
<% end %>

app/views/venta/articulos_credito.html.erb
<div class="page-header position-relative">
    <h1>
        Carrito de Compras
        <small>
            <i class="fa fa-angle-double-right"></i>
            Lista de Articulos con crédito
        </small>
    </h1>
</div><!--/.page-header-->

<% if current_usuario.tipo_usuario != 0 %>
<div class="row-fluid">
  <div class="span12">
    <!--PAGE CONTENT BEGINS-->
    <div class="row-fluid">
      <h3 class="header smaller lighter green">Agregar Artículos</h3>
    </div>

    <%= form_tag :action => "agregar_articulos", :html => {:role => "form", :class => "form-inline"} do %>
      
      <div class="input-prepend">
        <span class="add-on">
          <i class="fa fa-barcode"></i>
        </span>
        <%= text_field_tag :codigo, nil, :autofocus => true, :autocomplete => "off", :placeholder => "Código de barra" %>
      </div>

      <div class="input-prepend">
        <span class="add-on">
          <i class="fa fa-cube"></i>
        </span>
        <%= text_field_tag :cantidad, "1", :autocomplete => "off", :placeholder => "Cantidad de productos" %>
      </div>

      <%= submit_tag "Agregar", :class => "btn btn-sm btn-success" %>
    <% end %>
  
    <div class="row-fluid">
      <h3 class="header smaller lighter green">Lista de Artículos</h3>
    </div>

    <% if @articulos == nil %>
      <p>No existen productos ingresados al carrito</p>

    <% else %>
      <div class="row-fluid">
        <div class="span12">
          <table id="sample-table-1" class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Subtotal</th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @articulos.each do |articulo| %>
                <tr>
                  <td><%= Producto.find(articulo.producto_id).nombre %></td>
                  <td><%= articulo.cantidad %></td>
                  <td><%= Producto.find(articulo.producto_id).valor * articulo.cantidad %></td>
                  <td>
                    <%= link_to articulo, method: :delete, data: { confirm: '¿Estás seguro que deseas eliminar el articulo?'}, :class => "btn btn-mini btn-danger", :rel => "tooltip", :title => "Eliminar artículo" do%>
                      <i class="fa fa-trash bigger-120"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>  
            </tbody>
          </table>
        </div>
      </div>

      <div class="hr hr8 hr-double hr-dotted"></div>

      <div class="row-fluid">
        <div class="span5 pull-right">
          <h4 class="pull-right">
            Total Venta :
            <span class="red"> $<%= @ventum.total %></span>
          </h4>
        </div>
        <div class="span7 pull-left"> Información extra </div>
      </div>
    <% end %>
  </div>
</div>

<div class = "form-inline">
  <%= link_to venta_lista_path(@ventum), data: { confirm: '¿La venta está lista?' }, :class => "btn btn-primary" do %>
    <i class="fa fa-check"></i>
    Listo
  <% end %>

  <%= link_to cancelar_venta_path, data: {confirm: '¿Esta seguro que quiere cancelar la venta?'}, :class => "btn btn-warning" do %>
    <i class="fa fa-times"></i>
    Cancelar
  <% end %>
</div>

<% end %>

app/views/venta/credito.html.erb
<div class="page-header position-relative">
    <h1>
        Carrito de Compras
        <small>
            <i class="fa fa-angle-double-right"></i>
            Lista de Artículos
        </small>
    </h1>
</div><!--/.page-header-->

<% if current_usuario.tipo_usuario != 0 %>
<div class="row-fluid">
  <div class="span12">
    <!--PAGE CONTENT BEGINS-->

    <div class="row-fluid">
      <h3 class="header smaller lighter green">Detalles de Crédito</h3>
    </div>
    <%= form_tag :action => "seleccionar_cliente", :class => "form-horizontal" do %>

      <div class="control-group">
        <label>Cliente</label>
        <div class="controls">
          <%= select_tag :cliente, options_for_select(@clientes.collect { |cliente| [cliente.nombre.to_s + " " + cliente.apellido.to_s + " - " + cliente.rut.to_s, cliente.id] }), :include_blank => '- Todos los clientes -' %>
        </div>
      </div>

      <div class="actions">
        <%= submit_tag "Siguente", :class => "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

<div class="pull-right">
  <%= link_to cancelar_venta_path, data: {confirm: '¿Esta seguro que quiere cancelar la venta?'}, :class => "btn btn-warning" do %>
    <i class="fa fa-times"></i>
    Cancelar
  <% end %>
</div>
<% end %>

app/views/venta/edit.html.erb
<div class="page-header position-relative">
    <h1>
        Venta
        <small>
            <i class="fa fa-angle-double-right"></i>
            Editar una venta
        </small>
    </h1>
</div><!--/.page-header-->

<% if current_usuario.tipo_usuario != 0 %>
<div class="row-fluid">
  <div class="span12">
    <%= form_for(@ventum, :class => "form-horizontal") do |f| %>
      <% if @ventum.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@ventum.errors.count, "error") %> prohibited this ventum from being saved:</h2>

          <ul>
          <% @ventum.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="control-group">
        <%= f.label :usuario_id, :class => "control-label", :for => "form-field-1" %>
        <div class="controls">
          <%= f.number_field :usuario_id, :id => "form-field-1", :placeholder => "Usuario" %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :total, :class => "control-label", :for => "form-field-1" %>
        <div class="controls">
          <%= f.number_field :total, :id => "form-field-1", :placeholder => "Usuario" %>
        </div>
      </div>

      <div class="actions">
        <%= f.submit "Aceptar", :class => "btn btn-success"%>
      </div>
      
    <% end %>
  </div>
</div>

<div class = "form-inline pull-right">
  <%= link_to @ventum, :class => "btn btn-success" do %>
    <i class="fa fa-search"></i>
    Ver
  <% end %>
  
  <%= link_to venta_path, :class => "btn btn-warning" do %>
    <i class="fa fa-reply"></i>
    Volver
  <% end %>
</div>
<% end %>

app/views/venta/index.html.erb
<div class="page-header position-relative">
    <h1>
        Venta
        <small>
            <i class="fa fa-angle-double-right"></i>
            Lista de todas las ventas
        </small>
    </h1>
</div><!--/.page-header-->

<% if current_usuario.tipo_usuario != 0 %>
<div class="row-fluid">
  <div class="span12">
    <div class="row-fluid">
      <h3 class="header smaller lighter green">Filtros de Ventas por día</h3>
    </div>
    <!--PAGE CONTENT BEGINS-->
    <%= form_for_filterrific @filterrific,:html => {:class => "new_filterrific form-inline"}  do |f| %>
      <%# campo de busqueda%>
      <div class="row-fluid">
        <div class="span3">
          <div class="row-fluid">
            <label for="id-date-picker-1">Seleccionar día :</label>
          </div>
          <div class="control-group">
            <div class="row-fluid input-append">
              <%= f.text_field(:with_fecha, :id => "id-date-picker-1" , :class => 'filterrific-periodically-observed span10 date-picker', :autocomplete => "off" ) %>
              <span class="add-on">
                <i class="fa fa-calendar"></i>
              </span>
            </div>
          </div>
        </div>
      </div>
      <%= render_filterrific_spinner %>
    <% end %>

    <div class="row-fluid">
      <h3 class="header smaller lighter green">Lista de Ventas</h3>
    </div>
    <div class="pull-right">
      <%= link_to new_ventum_path, :class => "btn btn-primary", :accesskey => "n" do %>
        <i class="fa fa-plus"></i>
        Nueva Venta
      <% end %>
    </div>
    <table id="sample-table-1" class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th>Fecha</th>
          <th>Pagado</th>
          <th>Total</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @venta.each do |ventum| %>
          <% if ventum.terminada != false %>
            <tr>
              <td><%= ventum.fecha %></td>
              <td>
                <% if ventum.pagado %>
                  <span class="label label-success arrowed-in-right arrowed">Pagado</span>
                <% else %>
                  <span class="label label-important arrowed-in-right arrowed">No Pagado</span>
                <% end %>
              </td>
              <td><%= ventum.total %></td>
              <td>
                <%= link_to ventum, :class => "btn btn-mini btn-success", :rel => "tooltip", :title => "Ver detalles" do%>
                  <i class="fa fa-search bigger-120"></i>
                <% end %>

                <% if current_usuario.tipo_usuario == 1 %>
                  
                  <%= link_to edit_ventum_path(ventum), :class => "btn btn-mini btn-info", :rel => "tooltip", :title => "Editar" do%>
                    <i class="fa fa-edit bigger-120"></i>
                  <% end %>

                  <%= link_to ventum, method: :delete, data: { confirm: '¿Estás seguro que deseas eliminar la venta?'}, :class => "btn btn-mini btn-danger", :rel => "tooltip", :title => "Eliminar" do %>
                    <i class="fa fa-trash bigger-120"></i>
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>  
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<% end %>

<script type="text/javascript">
  $('.date-picker').datepicker().next().on(ace.click_event, function(){
    $(this).prev().focus();
  });
</script>

app/views/venta/new.html.erb
<div class="page-header position-relative">
    <h1>
        Venta
        <small>
            <i class="fa fa-angle-double-right"></i>
            Crear una nueva venta
        </small>
    </h1>
</div><!--/.page-header-->

<% if current_usuario.tipo_usuario != 0 %>
<div class = "form-horizontal">
	<%= link_to articulos_venta_path(@ventum), :class => "btn btn-primary", :accesskey => "n" do %>
		<i class="fa fa-money"></i>
		Venta al Contado
	<% end %>
	  
	<%= link_to credito_path(@ventum), :class => "btn btn-primary", :accesskey => "c" do %>
		<i class="fa fa-bomb"></i>
		Venta sin Cobrar
	<% end %>
</div>
<% end %>

app/views/venta/show.html.erb
<div class="page-header position-relative">
    <h1>
        Venta
        <small>
            <i class="fa fa-angle-double-right"></i>
            Detalle de la Venta
        </small>
    </h1>
</div><!--/.page-header-->

<% if current_usuario.tipo_usuario != 0 %>
<div class="row-fluid">
  <div class="span9">
    <div class="profile-info-row">
      <div class="profile-info-name"> Vendedor </div>

      <div class="profile-info-value">
        <span><%= Usuario.find(@ventum.usuario_id).nombre %></span>
      </div>
    </div>

    <div class="profile-info-row">
      <div class="profile-info-name"> Lista de Productos </div>

      <div class="profile-info-value">
      <% if @articulos == nil %>
        <span>No se registraron productos en esta venta</span>
      <% else %>
        <div class="row-fluid">
          <div class="span12">
            <table id="sample-table-1" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <th>Producto</th>
                  <th>Cantidad</th>
                </tr>
              </thead>

              <tbody>
                
                <% @articulos.each do |articulo| %>
                  <tr>
                    <td><%= Producto.find(articulo.producto_id).nombre %></td>
                    <td><%= articulo.cantidad %></td>
                  </tr>
                <% end %>  
                
              </tbody>
            </table>
          </div>
        </div>
      <% end %>
      </div>
    </div>

    <div class="profile-info-row">
      <div class="profile-info-name"> Total </div>

      <div class="profile-info-value">
        <span><%= @ventum.total %></span>
      </div>
    </div>
  </div>  
</div>

<div class = "form-inline pull-right">
  <%= link_to edit_ventum_path(@ventum), :class => "btn btn-info" do %>
    <i class="fa fa-edit"></i>
    Editar
  <% end %>
    
  <%= link_to venta_path, :class => "btn btn-warning" do %>
    <i class="fa fa-reply"></i>
    Volver
  <% end %>
</div>
<% end %>