config/routes.rb
NegocioChimbarongo::Application.routes.draw do

  get "welcome/index"

  devise_for :usuarios
  
  devise_scope :usuario do
    authenticated :usuario do
      root 'welcome#index'

      get "sign_out", :to => "devise/sessions#destroy"
      resources :usuarios

      resources :pagos

      match 'pagos' => 'pagos#seleccionar', :via => :get, as: :seleccionar

      match 'pagos/cliente/:id' => 'pagos#pagos', :via => :get, as: :pagos_cliente

      match 'pagos/pagar/venta/:id' => 'pagos#pagar', :via => :get, as: :pagar_venta

      match 'pagos/abonar/venta' => 'pagos#abonar', :via => :get, as: :abonar_venta

      match 'pagos/abonar/venta' => 'pagos#agregar_abono', :via => :post, as: :agregar_abono

      resources :alerta

      resources :tipo_productos

      resources :articulos

      resources :productos

      match 'venta/articulos' => 'venta#articulos', :via => :get, as: :articulos_venta

      match 'venta/articulos' => 'venta#articulos_credito', :via => :get, as: :articulos_credito

      match 'venta/creditos' => 'venta#credito', :via => :get, as: :credito

      match 'venta/creditos' => 'venta#seleccionar_cliente', :via => :post, as: :seleccionar_cliente

      match 'venta/articulos' => 'venta#agregar_articulos', :via => :post, as: :agregar_articulos

      get 'venta/:id/articulos/' => 'venta#venta_lista', as: :venta_lista

      get 'venta/cancelar' => 'venta#cancelar_venta', as: :cancelar_venta

      resources :venta

      resources :clientes

    end

    unauthenticated do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/controllers/pagos_controller.rb
class PagosController < ApplicationController
	layout "dashboard"

	def index
		@clientes = Cliente.all
	end

	def edit

	end

	def seleccionar
		@clientes = Cliente.all
	end

	def pagos
		@venta = Ventum.where(:cliente_id => params[:id])
	end

	def pagar
		@ventum = Ventum.find(params[:id])
		@ventum.pagado = true
		@ventum.save!

		flash[:notice] = "La venta ha sido pagada con exito"
		redirect_to action: "index"
	end

	def abonar
		if session[:ventum_id] == nil
			session[:ventum_id] = params[:id].to_i
		end
		@ventum = Ventum.find(session[:ventum_id])
		@articulos = Articulo.where(:ventum_id => @ventum.id)
	end

	def agregar_abono
		abono_actual = params[:abono].to_i
		@ventum = Ventum.find(session[:ventum_id])
		@ventum.abono += abono_actual

		if @ventum.abono > @ventum.total
			flash[:notice] = "Error - El abono es mayor que el total de la venta"
			redirect_to action: "abonar"
		elsif @ventum.abono = @ventum.total
			@ventum.pagado = true
			@ventum.save!
			session[:ventum_id] = nil
			flash[:notice] = "Se ha realizado el abono con exito"	
			redirect_to action: "index"
		else
			@ventum.save!
			session[:ventum_id] = nil
			flash[:notice] = "Se ha realizado el abono con exito"
			redirect_to action: "index"
		end
		
	end
end

app/helpers/pagos_helper.rb
module PagosHelper
end

app/views/pagos/abonar.html.erb
<div class="page-header position-relative">
    <h1>
        Pagos
        <small>
            <i class="fa fa-angle-double-right"></i>
            Abonar a la venta
        </small>
    </h1>
</div><!--/.page-header-->

<% if current_usuario.tipo_usuario != 0 %>
<div class="row-fluid">
  <div class="span12">
  	<div class="row-fluid">
      <h3 class="header smaller lighter green">Detalles de la Venta</h3>
    </div>
  </div>

  <div class="span9">
  	<div class="profile-info-row">
      <div class="profile-info-name"> Vendedor </div>

      <div class="profile-info-value">
        <span><%= Usuario.find(@ventum.usuario_id).nombre.to_s + " " + Usuario.find(@ventum.usuario_id).apellido.to_s %></span>
      </div>
    </div>

    <div class="profile-info-row">
      <div class="profile-info-name"> Lista de Productos </div>

      <div class="profile-info-value">
      <% if @articulos == nil %>
        <span>No se registraron productos en esta venta</span>
      <% else %>
        <div class="row-fluid">
          <div class="span12">
            <table id="sample-table-1" class="table table-striped table-bordered table-hover">
              <thead>
                <tr>
                  <th>Producto</th>
                  <th>Cantidad</th>
                </tr>
              </thead>

              <tbody>
                
                <% @articulos.each do |articulo| %>
                  <tr>
                    <td><%= Producto.find(articulo.producto_id).nombre %></td>
                    <td><%= articulo.cantidad %></td>
                  </tr>
                <% end %>  
                
              </tbody>
            </table>
          </div>
        </div>
      <% end %>
      </div>
    </div>

    <div class="profile-info-row">
      <div class="profile-info-name"> Total Venta </div>

      <div class="profile-info-value">
        <span><%= @ventum.total %></span>
      </div>
    </div>

    <div class="profile-info-row">
      <div class="profile-info-name"> Abonado </div>

      <div class="profile-info-value">
        <span><%= @ventum.abono %></span>
      </div>
    </div>

    <div class="profile-info-row">
      <div class="profile-info-name"> Total restante </div>

      <div class="profile-info-value">
        <span><%= (@ventum.total - @ventum.abono) %></span>
      </div>
    </div>
  </div> 

  <div class="span12">
    <div class="row-fluid">
      <h3 class="header smaller lighter green">Opciones de abono</h3>
    </div>
  </div>

  <div class="span12">
    <%= form_tag :action => "agregar_abono", :html => {:role => "form", :class => "form-inline"} do %>
      
      <div class="input-prepend">
        <span class="add-on">
          <i class="fa fa-money"></i>
        </span>
        <%= number_field_tag :abono, nil, :placeholder => "Abono para la venta" %>
      </div>

      <%= submit_tag "Listo", :class => "btn btn-sm btn-success" %>
    <% end %>
  </div>

</div>

<div class = "form-inline pull-right">
  <%= link_to pagos_path, :class => "btn btn-warning" do %>
    <i class="fa fa-times"></i>
    Cancelar
  <% end %>
</div>
<% end %>

app/views/pagos/index.html.erb
<div class="page-header position-relative">
    <h1>
        Pagos
        <small>
            <i class="fa fa-angle-double-right"></i>
            Lista de todos los pagos
        </small>
    </h1>
</div><!--/.page-header-->

<% if current_usuario.tipo_usuario != 0 %>
<div class="row-fluid">
  <div class="span12">
    <div class="row-fluid">
      <div class="span12">
        <table id="sample-table-1" class="table table-striped table-bordered table-hover">
        	<thead>
		        <tr>
              <th>Nombre</th>
              <th>Apellido</th>
              <th>Direccion</th>
              <th>Telefono</th>
              <th>Rut</th>
              <th>Nombre aval</th>
              <th>Apellido aval</th>
              <th>Rut aval</th>
              <th></th>
	          </tr>
	        </thead>

	        <tbody>
            <% @clientes.each do |cliente| %>
              <tr>
                <td><%= cliente.nombre %></td>
                <td><%= cliente.apellido %></td>
                <td><%= cliente.direccion %></td>
                <td><%= cliente.telefono %></td>
                <td><%= cliente.rut %></td>
                <td><%= cliente.nombre_aval %></td>
                <td><%= cliente.apellido_aval %></td>
                <td><%= cliente.rut_aval %></td>
	              <td>
	                <%= link_to pagos_cliente_path(cliente), :class => "btn btn-primary" do %>
                    <i class="fa fa-check"></i>
	                	Seleccionar
	                <% end %>
		            </td>
		          </tr>
		        <% end %>  
			    </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/pagos/pagar.html.erb
<h1><%= @number %></h1>

app/views/pagos/pagos.html.erb
<div class="page-header position-relative">
    <h1>
        Pagos
        <small>
            <i class="fa fa-angle-double-right"></i>
            Lista de todos los pagos
        </small>
    </h1>
</div><!--/.page-header-->

<% if current_usuario.tipo_usuario != 0 %>
<div class="row-fluid">
  <div class="span12">
    <div class="row-fluid">
      <div class="span12">
        <table id="sample-table-1" class="table table-striped table-bordered table-hover">
	      <thead>
	        <tr>
	          <th>Fecha</th>
	          <th>Nombre del Cliente</th>
	          <th>Rut del Cliente</th>
	          <th>Total</th>
	          <th>Abono</th>
	          <th></th>
	        </tr>
	      </thead>

	      <tbody>
	        <% @venta.each do |ventum| %>
	          <% if ventum.pagado == false %>
	            <tr>
	              <td><%= ventum.fecha %></td>
	              <td><%= Cliente.find(ventum.cliente_id).nombre.to_s + " " + Cliente.find(ventum.cliente_id).apellido.to_s %></td>
	              <td><%= Cliente.find(ventum.cliente_id).rut %></td>
	              <td><%= ventum.total %></td>
	              <td><%= ventum.abono %></td>
	              <td>
	                <%= link_to pagar_venta_path(:id => ventum.id), data: { confirm: '¿Estás seguro que deseas dar por pagada esta venta?'}, :class => "btn btn-primary" do%>
	                  <i class="fa fa-paypal"></i>
	                  Pagar
	                <% end %>
	                <%= link_to abonar_venta_path(:id => ventum.id), :class => "btn btn-primary" do%>
	                  <i class="fa fa-money"></i>
	                  Abonar
	                <% end %>
	              </td>
	            </tr>
	          <% end %>  
	        <% end %>
	      </tbody>
	    </table>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/pagos/seleccionar.html.erb
<div class="page-header position-relative">
    <h1>
        Pagos
        <small>
            <i class="fa fa-angle-double-right"></i>
            Seleccionar cliente a pagar
        </small>
    </h1>
</div><!--/.page-header-->