config/routes.rb
NegocioChimbarongo::Application.routes.draw do

  get "welcome/index"

  devise_for :usuarios
  
  devise_scope :usuario do
    authenticated :usuario do
      root 'welcome#index'

      get "sign_out", :to => "devise/sessions#destroy"
      resources :usuarios

      resources :pagos

      match 'pagos' => 'pagos#seleccionar', :via => :get, as: :seleccionar

      match 'pagos/cliente/:id' => 'pagos#pagos', :via => :get, as: :pagos_cliente

      match 'pagos/pagar/venta/:id' => 'pagos#pagar', :via => :get, as: :pagar_venta

      match 'pagos/abonar/venta' => 'pagos#abonar', :via => :get, as: :abonar_venta

      match 'pagos/abonar/venta' => 'pagos#agregar_abono', :via => :post, as: :agregar_abono

      resources :alerta

      resources :tipo_productos

      resources :articulos

      resources :productos

      match 'venta/articulos' => 'venta#articulos', :via => :get, as: :articulos_venta

      match 'venta/articulos' => 'venta#articulos_credito', :via => :get, as: :articulos_credito

      match 'venta/creditos' => 'venta#credito', :via => :get, as: :credito

      match 'venta/creditos' => 'venta#seleccionar_cliente', :via => :post, as: :seleccionar_cliente

      match 'venta/articulos' => 'venta#agregar_articulos', :via => :post, as: :agregar_articulos

      get 'venta/:id/articulos/' => 'venta#venta_lista', as: :venta_lista

      get 'venta/cancelar' => 'venta#cancelar_venta', as: :cancelar_venta

      resources :venta

      resources :clientes

    end

    unauthenticated do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/producto.rb
class Producto < ActiveRecord::Base

	#relaciones:
	#un producto tiene muchos articulos
	has_many :articulos
	#un producto tiene una alerta
	has_one :alerta
	#un producto pertenece a un tipo de producto
	belongs_to :tipo_producto

	after_save :revisar_alerta

	#validaciones
	validates :codigo, presence: true, uniqueness: true
	validates :nombre, presence: true
	validates :valor, presence: true
	validates :tipo_producto_id, presence: true
	validates :stock, presence: true

	filterrific(
		available_filters: [
			:with_codigo
		]
	)

	scope :with_codigo, lambda { |ref_codigo|
		where(:codigo => [*ref_codigo])
	}

	def revisar_alerta
		if self.stock < 6
			alert = Alertum.find_by(:producto_id => self.id)
			if alert == nil
				alerta = Alertum.create(:texto => self.nombre + " tiene un stock de " + self.stock.to_s + " productos", :producto_id => self.id)
			else
				alert.texto = self.nombre + " tiene un stock de " + self.stock.to_s + " productos"
				alert.save!
			end

		else
			alert = Alertum.find_by(:producto_id => self.id)
			if alert != nil
				alert.destroy
			end
		end
	end

end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  layout "dashboard"
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @filterrific = initialize_filterrific(
      Producto,
      params[:filterrific]
    ) or return
    
    @productos = Producto.filterrific_find(@filterrific).paginate(:page => params[:page])
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'El producto ha sido creado con exito.' }
        format.json { render action: 'show', status: :created, location: @producto }
      else
        format.html { render action: 'new' }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'El producto ha sido actualizado con exito.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:codigo, :nombre, :valor, :tipo_producto_id, :stock)
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<div class="row-fluid">
  <div class="span12">
    <%= form_for(@producto, :class => "form-horizontal") do |f| %>
      <% if @producto.errors.any? %>
        <div class="step-content row-fluid position-relative" id="step-container">
          <div class="step-pane active" id="step1">
              <h3 class="lighter block green"><%= pluralize(@producto.errors.count, "error") %>. El producto no puede ser guardado debido a:</h3>
              <ul>
                <% @producto.errors.full_messages.each do |msg| %>
                  <li>
                    <span class="help-inline"><%= msg %></span>
                  </li>
                <% end %>
              </ul>
          
          </div>
        </div>
      <% end %>

      <div class="control-group">
        <%= f.label :nombre, :class => "control-label", :for => "form-field-1" %>
        <div class="controls">
          <%= f.text_field :nombre, :id => "form-field-1", :placeholder => "Nombre del producto" %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :valor, :class => "control-label", :for => "form-field-1" %>
        <div class="controls">
          <%= f.number_field :valor, :id => "form-field-1", :placeholder => "Valor del producto" %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :tipo_producto_id, :class => "control-label", :for => "form-field-1" %>
        <div class="controls">
          <%= f.collection_select :tipo_producto_id, TipoProducto.all.collect, :id, :nombre, :class => "form-control"%>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :stock, :class => "control-label", :for => "form-field-1" %>
        <div class="controls">
          <%= f.number_field :stock, :id => "form-field-1", :placeholder => "Cantidad de artículos" %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :codigo, :class => "control-label", :for => "form-field-1" %>
        <div class="controls">
          <%= f.text_field :codigo, :id => "form-field-1", :placeholder => "Código" %>
        </div>
      </div>

      <div class="actions">
        <%= f.submit "Aceptar", :class => "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/productos/edit.html.erb
<div class="page-header position-relative">
    <h1>
        Producto
        <small>
            <i class="fa fa-angle-double-right"></i>
            Editar un producto
        </small>
    </h1>
</div><!--/.page-header-->

<% if current_usuario.tipo_usuario != 0 %>
<%= render 'form' %>

<div class = "form-inline pull-right">
	<%= link_to @producto, :class => "btn btn-info" do %>
		<i class="fa fa-search"></i>
		Ver
	<% end %>
	  
	<%= link_to productos_path, :class => "btn btn-warning" do %>
		<i class="fa fa-reply"></i>
		Volver
	<% end %>
</div>
<% end %>

app/views/productos/index.html.erb
<div class="page-header position-relative">
    <h1>
        Productos
        <small>
            <i class="fa fa-angle-double-right"></i>
            Lista de todos los productos
        </small>
    </h1>
</div><!--/.page-header-->

<% if current_usuario.tipo_usuario != 0 %>
<div class="row-fluid">
  <div class="span12">
    <div class="row-fluid">
      <h3 class="header smaller lighter green">Filtros de Productos por Código</h3>
    </div>
    <%= form_for_filterrific @filterrific,:html => {:class => "new_filterrific form-inline"}  do |f| %>
      <%# campo de busqueda%>
      <div class="row-fluid">
        <div class="span3">
          <div class="row-fluid">
            <label for="id-date-picker-1">Seleccionar código:</label>
          </div>
          <div class="control-group">
            <div class="row-fluid input-append">
              <%= f.text_field(:with_codigo, :id => "form-field-1", :placeholder => "Código de barra", :autocomplete => "off") %>
              <span class="add-on">
                <i class="fa fa-barcode"></i>
              </span>
            </div>
          </div>
        </div>
      </div>
      <%= render_filterrific_spinner %>
    <% end %>

    <div class="row-fluid">
      <h3 class="header smaller lighter green">Lista de Productos</h3>
    </div>
    <!--PAGE CONTENT BEGINS-->
    <div class="pull-right">
      <%= link_to new_producto_path, :class => "btn btn-primary" do %>
        <i class="fa fa-plus"></i>
        Nuevo Producto
      <% end %>
    </div>
    <br>
    <div class="row-fluid">
      <div class="span12">
        <table id="sample-table-1" class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
              <th>Codigo</th>
              <th>Nombre</th>
              <th>Valor</th>
              <th>Tipo producto</th>
              <th>Cantidad de productos</th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @productos.each do |producto| %>
              <tr>
                <td><%= producto.codigo %></td>
                <td><%= producto.nombre %></td>
                <td><%= producto.valor %></td>
                <td><%= TipoProducto.find(producto.tipo_producto_id).nombre %></td>
                <td><%= producto.stock %></td>
                <td>
                  <%= link_to producto, :class => "btn btn-mini btn-success", :rel => "tooltip", :title => "Ver detalles" do%>
                    <i class="fa fa-search bigger-120"></i>
                  <% end %>

                  <%= link_to edit_producto_path(producto), :class => "btn btn-mini btn-info", :rel => "tooltip", :title => "Editar" do%>
                    <i class="fa fa-edit bigger-120"></i>
                  <% end %>

                  <%= link_to producto, method: :delete, data: { confirm: '¿Estás seguro que deseas eliminar el producto?'}, :class => "btn btn-mini btn-danger", :rel => "tooltip", :title => "Eliminar" do %>
                    <i class="fa fa-trash bigger-120"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/productos/new.html.erb
<div class="page-header position-relative">
    <h1>
        Producto
        <small>
            <i class="fa fa-angle-double-right"></i>
            Crear un nuevo producto
        </small>
    </h1>
</div><!--/.page-header-->
<% if current_usuario.tipo_usuario != 0 %>
<%= render 'form' %>

<div class = "form-inline pull-right">
	<%= link_to productos_path, :class => "btn btn-warning" do %>
        <i class="fa fa-reply"></i>
		Volver
	<% end %>
</div>
<% end %>

app/views/productos/show.html.erb
<div class="page-header position-relative">
    <h1>
        Producto
        <small>
            <i class="fa fa-angle-double-right"></i>
            Resumen del producto
        </small>
    </h1>
</div><!--/.page-header-->

<% if current_usuario.tipo_usuario != 0 %>
<div class="row-fluid">
  <div class="span9">

    <div class="profile-info-row">
      <div class="profile-info-name"> Código </div>

      <div class="profile-info-value">
        <span><%= @producto.codigo %></span>
      </div>
    </div>

    <div class="profile-info-row">
      <div class="profile-info-name"> Nombre </div>

      <div class="profile-info-value">
        <span><%= @producto.nombre %></span>
      </div>
    </div>

    <div class="profile-info-row">
      <div class="profile-info-name"> Valor </div>

      <div class="profile-info-value">
        <span><%= @producto.valor %></span>
      </div>
    </div>

    <div class="profile-info-row">
      <div class="profile-info-name"> Tipo de Producto </div>

      <div class="profile-info-value">
        <span><%= @producto.tipo_producto.nombre %></span>
      </div>
    </div>

    <div class="profile-info-row">
      <div class="profile-info-name"> Cantidad </div>

      <div class="profile-info-value">
        <span><%= @producto.stock %></span>
      </div>
    </div>

  </div>
</div>

<div class = "form-inline pull-right">
  <%= link_to edit_producto_path(@producto), :class => "btn btn-success" do %>
    <i class="fa fa-edit"></i>
    Editar
  <% end %>
    
  <%= link_to productos_path, :class => "btn btn-warning" do %>
    <i class="fa fa-reply"></i>
    Volver
  <% end %>
</div>
<% end %>